### ISSUE TITLE
Polyglossia and hyperref interference when using french language

### ISSUE THREAD

**Issue by ivanrothfr** [reutenauer/polyglossia#469]
I have a warning when compiling the following code:

```
\documentclass{standalone}

\usepackage{polyglossia}
\setdefaultlanguage{french}
\usepackage{hyperref}

\begin{document}    
a
\end{document}
```

Warning is:
```
Failed to patch part for French
```

Configuration : xetex on TL2020 vanilla (polyglossia 1.51, hyperref 7.00e)

It disappears as soon as I disable either hyperref or setdefaultlanguage. It is still there, no matter how I change the order of the usepackage lines.

I also tried the [frenchpart=false] option for polyglossia as available starting version 1.51, but it does not compile and gives that error:
```
Package keyvalue Error: Unknown option 'frenchpart' for package polyglossia. \ProcessKeysOptions{polyglossia}
```

I asked about this on TeX.SX and got that answer from Ulrike Fischer:
```
well hyperref changes part (to insert an anchor) and polyglossia doesn't handle this case when trying to patch \part. Report it to polyglossia.
```

Tex.SX post: https://tex.stackexchange.com/questions/579644/polyglossia-and-hyperref-interference-when-using-french-language

**Comment by jspitz** [comment]
The document compiles for me without error. `\setdefaultlanguage[frenchpart=false]{french}` works as well.

Are you sure you have `polyglossia 1.51`?

**Comment by jspitz** [comment]
(I see the warning though)

**Comment by jspitz** [comment]
The issue should be fixed.

If you can, please download gloss-french.ldf from here (https://github.com/reutenauer/polyglossia/raw/master/tex/gloss-french.ldf) and see if this works for you.

I am still puzzled though why `frenchpart=false` didn't work for you.

**Comment by ivanrothfr** [comment]
I was applying the option with `\usepackage[frenchpart=false]{polyglossia}` instead of `\setdefaultlanguage[frenchpart=false]{french}`.

When using the option properly, it works without any warning. So, for the record, this works without any error or warning:
```
\documentclass{standalone}

\usepackage[french]{hyperref}

\usepackage{polyglossia}
\setdefaultlanguage[frenchpart=false]{french}

\begin{document}	
a
\end{document}
```

Thank you and sorry for my mistake.

**Comment by jspitz** [comment]
No problem. If you can, please still see whether the fix works for you without having to disable `frenchpart`.

**Comment by ivanrothfr** [comment]
I am still getting the warning, but only once. I was having it three times with the original gloss-french.ldf file.

**Comment by jspitz** [comment]
Hm but the output is correct now, isn't it? (i.e., "Première Partie" rather than "partie 1" with hyperref).

**Comment by ivanrothfr** [comment]
Yes, the output is now correct.

**Comment by jspitz** [comment]
So I suspect `\patchcmd `struggles with patching a copy done with `\let`. It patches, but it reports a patch failure.

@eg9 can you help here?

**Comment by yannl35133** [comment]
Not sure if this is worth mentioning, but this input still gives multiple warnings even with the file linked here.

```latex
\documentclass{moderncv}
\moderncvstyle{casual}
\moderncvcolor{red}

\usepackage{polyglossia}
\setmainlanguage{french}


\name{}{}

\begin{document}
\makecvtitle
\end{document}
```

The error message is the same, it is reported once at `file.tex:11` and twice at `file.aux:18`.

**Comment by jspitz** [comment]
Yes, the warning is still there, see https://github.com/reutenauer/polyglossia/issues/469#issuecomment-763720255

**Comment by jspitz** [comment]
> I am still getting the warning, but only once. I was having it three times with the original gloss-french.ldf file.

This warning's fixed now. Not yet the one from https://github.com/reutenauer/polyglossia/issues/469#issuecomment-780218336 though.

**Comment by jspitz** [comment]
> Not sure if this is worth mentioning, but this input still gives multiple warnings even with the file linked here (as opposed to [#469 (comment)](https://github.com/reutenauer/polyglossia/issues/469#issuecomment-763642853)).

This one's fixed as well. The reason here was that `moderncv` does not define `\part` (and `\@part`), but `hyperref` (which it loads) defines `\@part`.

So this was simply a false alarm
