### ISSUE TITLE
Does \selectlanguage "reset" language-specific options?

### ISSUE THREAD

**Issue by ivankokan** [reutenauer/polyglossia#488]
The following MWE
```latex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage{slovenian} % localalph=false by default

\usepackage[inline]{enumitem}

\begin{document}

\begin{enumerate*}[label=\alph*)]
\item 1 \item 2 \item 3 \item 4 \item 5 \item 6 \item 7 \item 8 \item 9
\item 10 \item 11 \item 12 \item 13 \item 14 \item 15 \item 16 \item 17 \item 18 \item 19
\item 20 \item 21 \item 22 \item 23 \item 24 \item 25
\end{enumerate*}

\selectlanguage[localalph]{slovenian}
\begin{enumerate*}[label=\alph*)]
\item 1 \item 2 \item 3 \item 4 \item 5 \item 6 \item 7 \item 8 \item 9
\item 10 \item 11 \item 12 \item 13 \item 14 \item 15 \item 16 \item 17 \item 18 \item 19
\item 20 \item 21 \item 22 \item 23 \item 24 \item 25
\end{enumerate*}

\selectlanguage{slovenian} % ???
\begin{enumerate*}[label=\alph*)]
\item 1 \item 2 \item 3 \item 4 \item 5 \item 6 \item 7 \item 8 \item 9
\item 10 \item 11 \item 12 \item 13 \item 14 \item 15 \item 16 \item 17 \item 18 \item 19
\item 20 \item 21 \item 22 \item 23 \item 24 \item 25
\end{enumerate*}

\end{document}

```
produces
![image](https://user-images.githubusercontent.com/1058211/112401952-e4efa780-8d0b-11eb-860b-1c4c46db4d4e.png)

One might expect that `\selectlanguage{slovenian} % ???` would have the same effect as `\selectlanguage[localalph=false]{slovenian}` in that place, but it does not. (I am aware that consecutive calls of `\selectlanguage` with the same given language are not so sound, but still...)

Is this the expected behavior? If it is, I cannot find adequate explanations in the manual - can you help?

**Comment by ivankokan** [comment]
On the other hand, the following MWE
```latex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage{croatian} % localalph=true by default

\usepackage[inline]{enumitem}

\begin{document}

\begin{enumerate*}[label=\alph*)]
\item 1 \item 2 \item 3 \item 4 \item 5 \item 6 \item 7 \item 8 \item 9
\item 10 \item 11 \item 12 \item 13 \item 14 \item 15 \item 16 \item 17 \item 18 \item 19
\item 20 \item 21 \item 22
\end{enumerate*}

\selectlanguage[localalph=false]{croatian} % ???
\begin{enumerate*}[label=\alph*)]
\item 1 \item 2 \item 3 \item 4 \item 5 \item 6 \item 7 \item 8 \item 9
\item 10 \item 11 \item 12 \item 13 \item 14 \item 15 \item 16 \item 17 \item 18 \item 19
\item 20 \item 21 \item 22
\end{enumerate*}

\selectlanguage{croatian} % ???
\begin{enumerate*}[label=\alph*)]
\item 1 \item 2 \item 3 \item 4 \item 5 \item 6 \item 7 \item 8 \item 9
\item 10 \item 11 \item 12 \item 13 \item 14 \item 15 \item 16 \item 17 \item 18 \item 19
\item 20 \item 21 \item 22
\end{enumerate*}

\end{document}
```
produces
![image](https://user-images.githubusercontent.com/1058211/112409527-efb13900-8d19-11eb-98af-75f4c01f48af.png)

Shouldn't `\selectlanguage[localalph=false]{croatian} % ???` cancel and `\selectlanguage{croatian} % ???` enable `localalph` again?

**Comment by jspitz** [comment]
First case is correct IMO, `localalph` status only changes if the option is explicitly given. The second case is fixed by defcdd12f46c2

**Comment by jspitz** [comment]
On the other hand, it is possible to initlalize all these bools on gloss load. But this would need to be done for many other booleans as well, for consistency. Basically all gloss files would need to be audited.

**Comment by ivankokan** [comment]
One more detail. While I was comparing these two cases, I found that `\noextras@slovenian` might be missing a conditional `\ifslovenian@localalph ... \fi%`, please check.

**Comment by ivankokan** [comment]
> First case is correct IMO, `localalph` status only changes if the option is explicitly given. The second case is fixed by [defcdd1](https://github.com/reutenauer/polyglossia/commit/defcdd12f46c274942a72f8e02be904d49c6806d)

@jspitz I tried with the fix, still the same outcome.

Based on your explanations, I expected to get:
a-z (22)
a-v (22) - the fix should address this, but it does not
a-v (22) - "localalph status only changes if the option is explicitly given", and here it is not explicitly given

**Comment by jspitz** [comment]
> @jspitz One more detail. While I was comparing these two cases, I found that `\noextras@slovenian` might be missing a conditional `\ifslovenian@localalph ... \fi%`, please check.

I seen that. It's not really necessary. But I can add it for consistency.

**Comment by jspitz** [comment]
> > First case is correct IMO, `localalph` status only changes if the option is explicitly given. The second case is fixed by [defcdd1](https://github.com/reutenauer/polyglossia/commit/defcdd12f46c274942a72f8e02be904d49c6806d)
> 
> @jspitz I tried with the fix, still the same outcome.
> 
> Based on your explanations, I expected to get:
> a-z (22)
> a-v (22) - the fix should address this, but it does not
> a-v (22) - "localalph status only changes if the option is explicitly given", and here it is not explicitly given

Can you try again?

**Comment by ivankokan** [comment]
Croatian: I added one more list with explicit `localalph=true` at the end of my original MWE.
![image](https://user-images.githubusercontent.com/1058211/112598115-66c7f980-8e0e-11eb-90bc-325885f17ba4.png)

Slovenian. The same MWE, the same result.

Now both are expected. ✔️ 

### Summary
> First case is correct IMO, `localalph` status only changes if the option is explicitly given.

> On the other hand, it is possible to initlalize all these bools on gloss load. But this would need to be done for many other booleans as well, for consistency. Basically all gloss files would need to be audited.

It is possible, but it would change so many things, i.e. does not make any sense to do it.

> > @jspitz One more detail. While I was comparing these two cases, I found that `\noextras@slovenian` might be missing a conditional `\ifslovenian@localalph ... \fi%`, please check.
> 
> I seen that. It's not really necessary. But I can add it for consistency.

It should have not been added to Croatian, actually. :D

**Comment by ivankokan** [comment]
> ...
> It is possible, but it would change so many things, i.e. does not make any sense to do it.

It seems that `localalph` (named that way, at least) has been implemented only for Croatian and Slovenian and now they are correct. Case truly closed.
